[2022-07-12 00:00:02,564] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: bitcoin_input.get_api scheduled__2022-07-11T00:00:00+00:00 [queued]>
[2022-07-12 00:00:02,580] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: bitcoin_input.get_api scheduled__2022-07-11T00:00:00+00:00 [queued]>
[2022-07-12 00:00:02,580] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 00:00:02,580] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-12 00:00:02,580] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 00:00:02,647] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): get_api> on 2022-07-11 00:00:00+00:00
[2022-07-12 00:00:02,652] {standard_task_runner.py:52} INFO - Started process 2100 to run task
[2022-07-12 00:00:02,656] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_input', 'get_api', 'scheduled__2022-07-11T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/projeto_api.py', '--cfg-path', '/tmp/tmpei7qqul6', '--error-file', '/tmp/tmpuk13rs4y']
[2022-07-12 00:00:02,657] {standard_task_runner.py:80} INFO - Job 13: Subtask get_api
[2022-07-12 00:00:02,773] {task_command.py:370} INFO - Running <TaskInstance: bitcoin_input.get_api scheduled__2022-07-11T00:00:00+00:00 [running]> on host 54ef6f590a3a
[2022-07-12 00:00:02,983] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bitcoin_input
AIRFLOW_CTX_TASK_ID=get_api
AIRFLOW_CTX_EXECUTION_DATE=2022-07-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-11T00:00:00+00:00
[2022-07-12 00:00:02,984] {http.py:97} INFO - Poking: 2022/7/11
[2022-07-12 00:00:02,995] {base.py:68} INFO - Using connection ID 'btc_get' for task execution.
[2022-07-12 00:00:02,997] {http.py:129} INFO - Sending 'GET' to url: https://www.mercadobitcoin.com.br/api/BTC/day-summary/2022/7/11
[2022-07-12 00:00:03,798] {http.py:142} ERROR - HTTP error: Forbidden
[2022-07-12 00:00:03,798] {http.py:143} ERROR - <!DOCTYPE html>
<html lang="en-US">
<head>
<title>Access denied</title>
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" href="/cdn-cgi/styles/errors.new.min.css" media="screen" />
<script>
(function(){if(document.addEventListener&&window.XMLHttpRequest&&JSON&&JSON.stringify){var e=function(a){var c=document.getElementById("error-feedback-survey"),d=document.getElementById("error-feedback-success"),b=new XMLHttpRequest;a={event:"feedback clicked",properties:{errorCode:1020,helpful:a,version:3}};b.open("POST","https://sparrow.cloudflare.com/api/v1/event");b.setRequestHeader("Content-Type","application/json");b.setRequestHeader("Sparrow-Source-Key","c771f0e4b54944bebf4261d44bd79a1e");
b.send(JSON.stringify(a));c.classList.add("feedback-hidden");d.classList.remove("feedback-hidden")};document.addEventListener("DOMContentLoaded",function(){var a=document.getElementById("error-feedback"),c=document.getElementById("feedback-button-yes"),d=document.getElementById("feedback-button-no");"classList"in a&&(a.classList.remove("feedback-hidden"),c.addEventListener("click",function(){e(!0)}),d.addEventListener("click",function(){e(!1)}))})}})();
</script>
<script>
         (function(){if(document.addEventListener){var c=function(){var b=document.getElementById("copy-label");document.getElementById("plain-ray-id");if(navigator.clipboard)navigator.clipboard.writeText("72957f179f7d6048");else{var a=document.createElement("textarea");a.value="72957f179f7d6048";a.style.top="0";a.style.left="0";a.style.position="fixed";document.body.appendChild(a);a.focus();a.select();document.execCommand("copy");document.body.removeChild(a)}b.innerText="Copied"};document.addEventListener("DOMContentLoaded",
function(){var b=document.getElementById("plain-ray-id"),a=document.getElementById("click-to-copy-btn");"classList"in b&&(b.classList.add("hidden"),a.classList.remove("hidden"),a.addEventListener("click",c))})}})();
      </script>
<script defer src="https://performance.radar.cloudflare.com/beacon.js"></script>
</head>
<body>
<div class="main-wrapper" role="main">
<div class="header section">
<h1>
<span class="error-description">Access denied</span>
<span class="code-label">Error code <span>1020</span></span>
</h1>
<div class="large-font">
<p>You do not have access to www.mercadobitcoin.com.br.</p><p>The site owner may have set restrictions that prevent you from accessing the site. Contact the site owner for access or try loading the page again.</p>
</div>
</div>
</div>
<div>
<div class="clearfix section">
<div class="column know-more">
<h2 class="large-font">Additional information</h2>
<p>The access policies of a site define which visits are allowed. Your current visit is not allowed according to those policies.</p><p>Only the site owner can change site access policies.</p>
</div>
<div class="column know-more">
<h2 class="large-font">I am the site owner</h2>
<p class="ray-id-wrapper">
Ray ID:
<span class="plain-ray-id" id="plain-ray-id">
72957f179f7d6048
</span>
<button class="click-to-copy-btn hidden" id="click-to-copy-btn" title="Click to copy Ray ID" type="button">
<span class="ray-id">72957f179f7d6048</span><span class="copy-label" id="copy-label">Copy</span>
</button>
</p>
<ol>
<li>
Search the
<a rel="noopener noreferrer" href="https://dash.cloudflare.com/?to=/:account/:zone/firewall" target="_blank">Firewall Events Log</a>
<img class="external-link" title="Opens in new tab" src="/cdn-cgi/images/external.png" alt="External link">
for the above Ray ID.
</li>
<li>Examine and assess the details of the access policy.</li>
</ol>
<br>
<a rel="noopener noreferrer" href="https://support.cloudflare.com/hc/articles/360029779472-Troubleshooting-Cloudflare-1XXX-errors#error1020" target="_blank">Troubleshooting guide</a>
<img class="external-link" title="Opens in new tab" src="/cdn-cgi/images/external.png" alt="External link">
</div>
</div>
<div class="clearfix footer section" role="contentinfo">
<div class="column">
<div class="feedback-hidden py-8 text-center" id="error-feedback">
<div id="error-feedback-survey" class="footer-line-wrapper">
Was this page helpful?
<button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-yes" type="button">Yes</button>
<button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-no" type="button">No</button>
</div>
<div class="feedback-success feedback-hidden" id="error-feedback-success">
Thank you for your feedback!
</div>
</div>
</div>
<div class="column footer-line-wrapper text-center">
Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com" target="_blank">Cloudflare</a>
<img class="external-link" title="Opens in new tab" src="/cdn-cgi/images/external.png" alt="External link">
</div>
</div>
</div>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194" integrity="sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw==" data-cf-beacon='{"rayId":"72957f179f7d6048","token":"bdd41a57ca1a467086229b46045794af","version":"2022.6.0","si":100}' crossorigin="anonymous"></script>
</body>
</html>

[2022-07-12 00:00:03,817] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 140, in check_response
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.mercadobitcoin.com.br/api/BTC/day-summary/2022/7/11

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 277, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 112, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 103, in poke
    extra_options=self.extra_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 130, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 183, in run_and_check
    self.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 144, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 403:Forbidden
[2022-07-12 00:00:03,999] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bitcoin_input, task_id=get_api, execution_date=20220711T000000, start_date=20220712T000002, end_date=20220712T000003
[2022-07-12 00:00:04,085] {standard_task_runner.py:97} ERROR - Failed to execute job 13 for task get_api (403:Forbidden; 2100)
[2022-07-12 00:00:04,118] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-12 00:00:04,242] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-12 00:16:00,641] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: bitcoin_input.get_api scheduled__2022-07-11T00:00:00+00:00 [queued]>
[2022-07-12 00:16:00,708] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: bitcoin_input.get_api scheduled__2022-07-11T00:00:00+00:00 [queued]>
[2022-07-12 00:16:00,728] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 00:16:00,729] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-12 00:16:00,730] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 00:16:00,961] {taskinstance.py:1377} INFO - Executing <Task(SimpleHttpOperator): get_api> on 2022-07-11 00:00:00+00:00
[2022-07-12 00:16:00,967] {standard_task_runner.py:52} INFO - Started process 2745 to run task
[2022-07-12 00:16:00,971] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_input', 'get_api', 'scheduled__2022-07-11T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/projeto_api.py', '--cfg-path', '/tmp/tmpo4uwrjwh', '--error-file', '/tmp/tmpbc8glznz']
[2022-07-12 00:16:00,972] {standard_task_runner.py:80} INFO - Job 18: Subtask get_api
[2022-07-12 00:16:01,342] {task_command.py:370} INFO - Running <TaskInstance: bitcoin_input.get_api scheduled__2022-07-11T00:00:00+00:00 [running]> on host 54ef6f590a3a
[2022-07-12 00:16:02,428] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bitcoin_input
AIRFLOW_CTX_TASK_ID=get_api
AIRFLOW_CTX_EXECUTION_DATE=2022-07-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-11T00:00:00+00:00
[2022-07-12 00:16:02,429] {http.py:102} INFO - Calling HTTP method
[2022-07-12 00:16:02,445] {base.py:68} INFO - Using connection ID 'btc_get' for task execution.
[2022-07-12 00:16:02,447] {http.py:129} INFO - Sending 'GET' to url: https://www.mercadobitcoin.com.br/api/BTC/day-summary/2022/7/11
[2022-07-12 00:16:02,634] {http.py:142} ERROR - HTTP error: Forbidden
[2022-07-12 00:16:02,634] {http.py:143} ERROR - <!DOCTYPE html>
<html lang="en-US">
<head>
<title>Access denied</title>
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" href="/cdn-cgi/styles/errors.new.min.css" media="screen" />
<script>
(function(){if(document.addEventListener&&window.XMLHttpRequest&&JSON&&JSON.stringify){var e=function(a){var c=document.getElementById("error-feedback-survey"),d=document.getElementById("error-feedback-success"),b=new XMLHttpRequest;a={event:"feedback clicked",properties:{errorCode:1020,helpful:a,version:3}};b.open("POST","https://sparrow.cloudflare.com/api/v1/event");b.setRequestHeader("Content-Type","application/json");b.setRequestHeader("Sparrow-Source-Key","c771f0e4b54944bebf4261d44bd79a1e");
b.send(JSON.stringify(a));c.classList.add("feedback-hidden");d.classList.remove("feedback-hidden")};document.addEventListener("DOMContentLoaded",function(){var a=document.getElementById("error-feedback"),c=document.getElementById("feedback-button-yes"),d=document.getElementById("feedback-button-no");"classList"in a&&(a.classList.remove("feedback-hidden"),c.addEventListener("click",function(){e(!0)}),d.addEventListener("click",function(){e(!1)}))})}})();
</script>
<script>
         (function(){if(document.addEventListener){var c=function(){var b=document.getElementById("copy-label");document.getElementById("plain-ray-id");if(navigator.clipboard)navigator.clipboard.writeText("7295968038f6a496");else{var a=document.createElement("textarea");a.value="7295968038f6a496";a.style.top="0";a.style.left="0";a.style.position="fixed";document.body.appendChild(a);a.focus();a.select();document.execCommand("copy");document.body.removeChild(a)}b.innerText="Copied"};document.addEventListener("DOMContentLoaded",
function(){var b=document.getElementById("plain-ray-id"),a=document.getElementById("click-to-copy-btn");"classList"in b&&(b.classList.add("hidden"),a.classList.remove("hidden"),a.addEventListener("click",c))})}})();
      </script>
<script defer src="https://performance.radar.cloudflare.com/beacon.js"></script>
</head>
<body>
<div class="main-wrapper" role="main">
<div class="header section">
<h1>
<span class="error-description">Access denied</span>
<span class="code-label">Error code <span>1020</span></span>
</h1>
<div class="large-font">
<p>You do not have access to www.mercadobitcoin.com.br.</p><p>The site owner may have set restrictions that prevent you from accessing the site. Contact the site owner for access or try loading the page again.</p>
</div>
</div>
</div>
<div>
<div class="clearfix section">
<div class="column know-more">
<h2 class="large-font">Additional information</h2>
<p>The access policies of a site define which visits are allowed. Your current visit is not allowed according to those policies.</p><p>Only the site owner can change site access policies.</p>
</div>
<div class="column know-more">
<h2 class="large-font">I am the site owner</h2>
<p class="ray-id-wrapper">
Ray ID:
<span class="plain-ray-id" id="plain-ray-id">
7295968038f6a496
</span>
<button class="click-to-copy-btn hidden" id="click-to-copy-btn" title="Click to copy Ray ID" type="button">
<span class="ray-id">7295968038f6a496</span><span class="copy-label" id="copy-label">Copy</span>
</button>
</p>
<ol>
<li>
Search the
<a rel="noopener noreferrer" href="https://dash.cloudflare.com/?to=/:account/:zone/firewall" target="_blank">Firewall Events Log</a>
<img class="external-link" title="Opens in new tab" src="/cdn-cgi/images/external.png" alt="External link">
for the above Ray ID.
</li>
<li>Examine and assess the details of the access policy.</li>
</ol>
<br>
<a rel="noopener noreferrer" href="https://support.cloudflare.com/hc/articles/360029779472-Troubleshooting-Cloudflare-1XXX-errors#error1020" target="_blank">Troubleshooting guide</a>
<img class="external-link" title="Opens in new tab" src="/cdn-cgi/images/external.png" alt="External link">
</div>
</div>
<div class="clearfix footer section" role="contentinfo">
<div class="column">
<div class="feedback-hidden py-8 text-center" id="error-feedback">
<div id="error-feedback-survey" class="footer-line-wrapper">
Was this page helpful?
<button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-yes" type="button">Yes</button>
<button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-no" type="button">No</button>
</div>
<div class="feedback-success feedback-hidden" id="error-feedback-success">
Thank you for your feedback!
</div>
</div>
</div>
<div class="column footer-line-wrapper text-center">
Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com" target="_blank">Cloudflare</a>
<img class="external-link" title="Opens in new tab" src="/cdn-cgi/images/external.png" alt="External link">
</div>
</div>
</div>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194" integrity="sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw==" data-cf-beacon='{"rayId":"7295968038f6a496","token":"bdd41a57ca1a467086229b46045794af","version":"2022.6.0","si":100}' crossorigin="anonymous"></script>
</body>
</html>

[2022-07-12 00:16:02,669] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 140, in check_response
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.mercadobitcoin.com.br/api/BTC/day-summary/2022/7/11

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 104, in execute
    response = http.run(self.endpoint, self.data, self.headers, self.extra_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 130, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 183, in run_and_check
    self.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 144, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 403:Forbidden
[2022-07-12 00:16:02,942] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bitcoin_input, task_id=get_api, execution_date=20220711T000000, start_date=20220712T001600, end_date=20220712T001602
[2022-07-12 00:16:03,238] {standard_task_runner.py:97} ERROR - Failed to execute job 18 for task get_api (403:Forbidden; 2745)
[2022-07-12 00:16:03,304] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-12 00:16:03,572] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
